
### Load in data ###
# report = read.csv(file = list.files(path = ".", pattern = "*Report.csv", full.names = T))

#' @title Molecular Trait Analysis
#' @description This function performs a comprehensive analysis of molecular traits from a given report
#' @param report A data frame containing the molecular report data generated by Formularity (Tolić et al, 2017 - Anal. Chem.)
#' @return A data frame of the molecular traits.
#' @rdname molTrait
#' @export 
molTrait <- function(report){
  
  # Separating molecular information and peak data
  emeta = report[, c("Mass", "C", "H", "O", "N", "C13", "S", "P", "Na", "El_comp", 
                     "Class", "NeutralMass", "Error_ppm", "Candidates")]
  edata = report[,-which(colnames(report) %in% c("C", "H", "O", "N", "C13", "S", "P", "Na", "El_comp", 
                                                 "Class", "NeutralMass", "Error_ppm", "Candidates"))]
  rm("report") # Removing report
  
  #### Creating empty factors data ####
  fdata = data.frame(Sample_ID = colnames(edata)[-1], Location = "Somewhere")
  
  ### Convert data and remove isotopic peaks ###
  peak_icr = as.peakData(e_data = edata, f_data = fdata, e_meta = emeta, edata_cname = "Mass", mass_cname = "Mass",
                         fdata_cname = "Sample_ID", c_cname = "C", h_cname = "H", o_cname = "O", n_cname = "N", s_cname = "S",
                         p_cname = "P", isotopic_cname = "C13", isotopic_notation = "1")
  
  
  ### Calculating derived statistics ####
  peak_icr = compound_calcs(peak_icr)
  
  ### Assigning compound classes ###
  peak_icr = assign_class(peak_icr, boundary_set = "bs1")
  peak_icr = assign_class(peak_icr, boundary_set = "bs2")
  peak_icr = assign_class(peak_icr, boundary_set = "bs3")
  
  ### Filtering peaks ###
  filter_obj = mass_filter(peak_icr)
  peak_icr = applyFilt(filter_obj, peak_icr, min_mass = 200, max_mass = 900)
  
  return(peak_icr$e_meta)
}

